# Site
name: 'RJCreators'
description: 'RJCreators'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'jalpahmsi@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jalpa:
      name:           Jalpa Sangani
      site:           https://rjcreators.github.io
      avatar:         assets/images/avatar.jpeg
      bio:            "Hi, I am Jalpa Sangani, the author of RJCreator"
      email:          jalpahmsi@gmail.com
      twitter:        https://twitter.com/rjcreators1

    ruchi:
      name:           Ruchi
      site:           https://rjcreators.github.io
      avatar:         assets/images/avatar.jpeg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          jalpahmsi@gmail.com
      twitter:        https://twitter.com/rjcreators1
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jalpa
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]